#!/usr/bin/env bash

# Check for Homebrew and install if we don't have it
if [ ! $(command -v brew) ]; then
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Update Homebrew recipes
brew update

# Install all our dependencies with bundle (See Brewfile)
brew tap homebrew/bundle
brew bundle install --file $DOTFILES/Brewfile

# Cleanup brew
brew cask cleanup
brew cleanup

# linking apps
# TODO: fix app in a different way
# brew linkapps neovim-dot-app

# Running instalation of backblaze
if [ ! -e "/Applications/Backblaze.app" ]; then
  open '/usr/local/Caskroom/backblaze/latest/Backblaze Installer.app'
fi
