#!/usr/bin/env bash

# Installing nvm
if test ! $(command -v nvm); then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
fi

# Loading nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"

# installing node versions
nvm install 4.3.2
nvm install 8.10

nvm alias default 8.10

# installing global npm packages for node 4
nvm use 4
npm install -g serverless@0.5.6   # old serverless framework

# installing global npm packages for node 8
nvm use 8
npm install -g npm@latest         # latest npm
npm install -g npm-check          # package versions management tool
npm install -g @vue/cli vue-cli   # vue.js setup templates
npm install -g http-server        # static http server
