#!/usr/bin/env bash

# Make ZSH the default shell environment
if [[ ! "$SHELL" =~ zsh$ ]]; then
  # making a "beep" sound
  printf "\a\n\n"
  # switching shell to be zsh
  chsh -s $(which zsh)
fi

# Removes .zshrc from $HOME (if it exists) and symlinks the .zshrc file from the .dotfiles
rm -rf $HOME/.zshrc
ln -s $DOTFILES/.zshrc $HOME/.zshrc

# Cloning oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
# export ZSH_CUSTOM=$HOME/.dotfiles
export ZSH_CUSTOM=$ZSH/custom

# Installing oh-my-zsh
if [ ! -e "$ZSH" ]; then
  echo "Installing oh-my-zsh..."
  git clone https://github.com/robbyrussell/oh-my-zsh.git "$ZSH"
fi

# Installing spaceship-prompt theme
if [ ! -e "$ZSH_CUSTOM/themes/spaceship-prompt" ]; then
  echo "Installing spaceship-prompt zsh theme..."
  git clone https://github.com/denysdovhan/spaceship-prompt.git "$ZSH_CUSTOM/themes/spaceship-prompt"
  ln -s "$ZSH_CUSTOM/themes/spaceship-prompt/spaceship.zsh-theme" "$ZSH_CUSTOM/themes/spaceship.zsh-theme"
fi

# Installing zsh-nvm custom plugin
if [ ! -e "$ZSH_CUSTOM/plugins/zsh-nvm" ]; then
  echo "Installing zsh-nvm plugin..."
  git clone https://github.com/lukechilds/zsh-nvm "$ZSH_CUSTOM/plugins/zsh-nvm"
fi

# Creating symlinks for zsh extensions
for file in $DOTFILES/zsh/*.zsh; do
  [ -e "$file" ] || continue
  extension=$(basename $file)
  # if extension is not linked yet
  if [ ! -e "$ZSH_CUSTOM/$extension" ]; then
    # link it
    ln -s "$DOTFILES/zsh/$extension" "$ZSH_CUSTOM/$extension"
  fi
done
